### ISSUE TITLE
数据能设置时间范围吗, 假如到了2020年, 感觉就一片空白了

### ISSUE THREAD

**Issue by czy0729** [weizhenye/bangumi-mosaic-tile#1]
如题

**Comment by weizhenye** [comment]
我记得我写的是当前日期往前一年，不是按整年来的，2020 年不会一片空白

**Comment by czy0729** [comment]
就等时间来验证一下 bgm38

**Comment by czy0729** [comment]
![image](https://user-images.githubusercontent.com/13514316/88069423-03f9d080-cba4-11ea-938c-d11baa81ee98.png)
已经用上, 感觉很棒 b38

**Comment by weizhenye** [comment]
我看你的 Bangumi-OSS 有 2M hits/month 我好怕啊，bangumi-mosaic-tile 数据库白嫖的 Google Cloud Datastore，每日 5 万免费配额，用完就挂的（

**Comment by czy0729** [comment]
不怕 每日最多500 我一个人1天最多请求一次

**Comment by czy0729** [comment]
不怕 登陆了的UV每日最多500左右 多也不会过1000 然后我一个人1天最多请求一次 
而且这种页面通常就好奇会点一下 看过后通常就不再进入
